### ISSUE TITLE
htmlentities() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by anrainer** [simonschaufi/gkh_rss_import#1]
Hi Simon,

I have an Oops Error saying:

htmlentities() expects parameter 1 to be string, null given

Typo3              : 7.6.32
gkh_rss_import: 6.0.4

Am I doing something wrong?

Kind regards

Andreas

**Comment by simonschaufi** [comment]
Hi Andreas, can you send me the link to the rss feed? htmlentities is used a couple of times and I need to know which one breaks for you. i use a Wordpress feed without problems

**Comment by anrainer** [comment]
Hi Simon,

sorry, of course, I forgot that. Here it is:

http://www.sportschau.de/sportschauindex100_type-rss.feed

Thanks for your reply ;)

Andreas

**Comment by simonschaufi** [comment]
Fixed in v6.0.5

**Comment by anrainer** [comment]
Hi Simon, thanks for fixing! I upgraded to 6.0.5 and it works ;) Do you have a PayPal Donate Button somewhere? Kind Regards, Andreas

**Comment by simonschaufi** [comment]
@anrainer yes, there is a donate button on https://extensions.typo3.org/extension/gkh_rss_import

**Comment by simonschaufi** [comment]
@anrainer Thank you very much for your donation! Still I have one question. There are 2 different ways of sending money via Paypal. One is for "payment" and the other one is for "personal" money transfer. You chose the "payment" version and for the payment version I have to pay some transaction fees. I would like to return the money back to you so you can send it with the "personal" transfer. Would that be ok for you? I would have loved to write that personally to you but didn't find any email address at the transaction details.

**Comment by anrainer** [comment]
Hi Simon, my address is a.rainer@nea-net.de, please send me yours. I think we can use German then? Regards, Andreas

**Comment by simonschaufi** [comment]
@anrainer wrote you an email. Hope to hear from you soon. Happy new year! :tada:
