### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by Babcom55** [simonschaufi/gkh_rss_import#11]
# Support
Hi , I am encountering some trouble using this extension on typo3 10.4.12
## Description
When I am using the extentsion , images from the rss feed are not displayed, I only see the marks ###IMAGE###.
here is the rss feed : 
https://www.weblex.fr/passerelle-json?user=306-7349&pass=6a5ca39dbf
Thx a lot for your any help

## Screenshots

![image](https://user-images.githubusercontent.com/37980588/105312630-01f9e400-5bbe-11eb-81a7-329948cbe050.png)

**Comment by simonschaufi** [comment]
Hi, thank you for providing the feed url, that helps a lot. Unfortunately the feed is invalid, have a look at the validator here https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.weblex.fr%2Fpasserelle-json%3Fuser%3D306-7349%26pass%3D6a5ca39dbf

**Comment by Babcom55** [comment]
Ok, I'll check again with the feed provider : (45$/month ) to get that feed !!! 
Image tag is sill there
I also corrected the 'no' under 'Remove HTML', thx, it didn't change anything.

**Comment by simonschaufi** [comment]
The problem with the image is that the feed is invalid: `<image><title>WebLex</title><url>https://www.weblex.fr/images/flux_actus/voitureelectrique.jpg</url></image>`. The image tag should only contain an url and no sub tags. At least this is the way how the wordpress feed looks like. An image within the description should now be shown.

**Comment by Babcom55** [comment]
ok I get it, thx a lot for your time. And by the way you are right about  not releasing something that is not standard.

**Comment by simonschaufi** [comment]
If you feel like supporting me financially to keep maintaining this extension also for future TYPO3 versions, I would highly appreciate your sponsorship!

**Comment by Babcom55** [comment]
I made a modest donation according to my means, I wish I could do more. Now I have see what you meant by Xclass :). Thx again

**Comment by simonschaufi** [comment]
Thank you very much!

PS: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Xclasses/Index.html

You just extend the LastRssService, register the new class in ext_localconf.php and then copy lastRss to your own place and create a new instance yourself where you have all the freedom you want :smile:

**Comment by Babcom55** [comment]
Oh ok, unfortunately I'm not as good developper as, you. I've built only one extention in my all life and it was with the typo3 tutorial. So modifying you would be too difficult for me. I've found a workaround, less pretty but efficient : https://laraume-conseils.com/rss_import_feed.php . It's a simple php page and I use a pagelink to display it. 
Thx again for your time .
