### ISSUE TITLE
Invalid cache identifier for image with parameters

### ISSUE THREAD

**Issue by frodocat** [simonschaufi/gkh_rss_import#13]
When I installed the extension and put it on a page, edit the plugin and then view my page I get a typo3 error message.  So I can't see the page anymore. I used the latest version of the plugin 7.0.2 and I use typo3 version 10.4.13.
This is the error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1233058486: "ff85589e3e130c31938d33f3f65f9beb96e30a79sl=1" is not a valid cache entry identifier. | InvalidArgumentException thrown in file /data/html/typo3source/versie10/typo3_src-10.4.13/typo3/sysext/core/Classes/Cache/Frontend/AbstractFrontend.php in line 91. Requested URL: ......

**Comment by simonschaufi** [comment]
as this is not reproducable for me, can you please try to debug yourself how the wrong cache identifier is generated?

**Comment by frodocat** [comment]
I have sorted out what the problem is. The problem is that I want to show this feed: https://community.data.4tu.nl/feed/ but this gives typo3 errors. Do you know why?

**Comment by simonschaufi** [comment]
@frodocat Looks like because of their weird looking image url: https://i1.wp.com/community.data.4tu.nl/wp-content/uploads/2020/10/cropped-logo-4-1.png?fit=32%2C32&#038;ssl=1 with additional parameters.

**Comment by simonschaufi** [comment]
@frodocat Looks like because of their weird looking image url: https://i1.wp.com/community.data.4tu.nl/wp-content/uploads/2020/10/cropped-logo-4-1.png?fit=32%2C32&#038;ssl=1 with additional parameters.

**Comment by frodocat** [comment]
@simonschaufi I solved the rss issue with the strange url. So now I can see the feed with your extension. Thanks for helping me!

**Comment by simonschaufi** [comment]
@frodocat how did you solve a thing which is on wordpress?
