### ISSUE TITLE
Error on install with ddev

### ISSUE THREAD

**Issue by Trayshar** [simonschaufi/gkh_rss_import#25]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [X] Can you reproduce the problem on TYPO3 v11.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v12.0
* [ ] Can you reproduce the problem on TYPO3 dev-main
* [X] Did you [perform a search](https://github.com/simonschaufi/gkh_rss_import/issues)
  to see if your bug or enhancement is already reported?

## Description

Extension setup script crashes on fresh ddev TYPO3 v11.5 installation

## Steps to Reproduce

1. Install a fresh TYPO3 installation using [ddev](https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Installation/TutorialDdev.html)
2. Install this dependency using composer: `ddev composer req gkh/gkh-rss-import`
3. Run the extension setup command as described [here](https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Extensions/Management.html#setup-the-extension): `ddev typo3cms extension:setup`

### Expected behavior

The setup command exits without error.

### Actual behavior

```
[ TYPO3\CMS\Core\Error\Exception ]
Warning: Undefined array key "gkh_rss_import_image" in /var/www/html/public/typo3conf/ext/gkh_rss_import/ext_localconf.php line 25

Failed to run typo3cms extension:setup: exit status 1
```

## Versions

`gkh/gkh-rss-import: v9.0.2`
`typo3: v11.5.16`
`composer: v2.4.2`

**Comment by simonschaufi** [comment]
This has to do with PHP 8. I'll provide a fix asap.

**Comment by EricBode** [comment]
This issue can be closed as it already has been fixed by merged PR https://github.com/simonschaufi/gkh_rss_import/pull/24
