### ISSUE TITLE
TCA internal_type of field "template" in table tt_content must be set to "db" or "folder".

### ISSUE THREAD

**Issue by kurtwithslc** [simonschaufi/gkh_rss_import#3]
## Description
If trying to insert the plugin as content element, i got this Error:

#1438780511 UnexpectedValueException
TCA internal_type of field "template" in table tt_content must be set to "db" or "folder".

## Steps to Reproduce

1. Install plugin from TER
2. create Template and insert gkh_rss_mport template
3. try to create content element with this plugin

### Expected behavior

content element with plugin can be created

### Actual behavior

Error above

## Versions

gkh_rss_import 7.0.0; Typo3 10.4.9, PHP 7.3 FPM

**Comment by simonschaufi** [comment]
I'm really sorry that I didn't test properly. I will fix it asap!

**Comment by simonschaufi** [comment]
@kurtwithslc @tlaxcala what do you prefer: migrate the template setting to FAL or just use an input field? I tried FAL but it's very complicated.

**Comment by simonschaufi** [comment]
@kurtwithslc @tlaxcala I provided a PR where I got it working with FAL and also typoscript via EXT:extension. Can you please check my PR if that works for you?

**Comment by kurtwithslc** [comment]
Made test with 7.0.1:
- no errors
- rss feed is shown (used standard template RssImport.html)
- links in ###IMAGE### and ###URL### seems to be incorrect, cause they show rss-feed an not the web-page as expected
- tested with this feed: http://www.aponet.de/rss/news.html?type=61418134
- link ###URL### generated is: 
-- https://www.aponet.de/startseite/rss/news.html?type=61418134&cHash=55193058dc58a9ad41c427d756e2b949
-- correct link should be imho: https://www.aponet.de/startseite/rss/news.html

**Comment by simonschaufi** [comment]
@kurtwithslc thanx. which typo3 version are you testing on?

**Comment by kurtwithslc** [comment]
Typo 3 10.4.9

**Comment by simonschaufi** [comment]
@kurtwithslc I'm not manipulating the urls in any way, the links are wrong in the xml output already. Are you maintaining this website?
