### ISSUE TITLE
Integration in Crowdin is uncomplete

### ISSUE THREAD

**Issue by prathers** [simonschaufi/gkh_rss_import#42]
The Crowdin integration for the repository need some attention: https://crowdin.com/project/typo3-extension-gkhrssimport/apps/system/github

**Comment by simonschaufi** [comment]
I checked it and I don't see any issue. What exactly do I need to do?

**Comment by prathers** [comment]
Perfect, thanks. Everything is running

**Comment by simonschaufi** [comment]
ok, how can i make sure that crowdin does NOT create any pull requests like here https://github.com/simonschaufi/gkh_rss_import/pull/45 ?
